#!/bin/sh
OUTPUT="./modlist.md"

echo "# Modlist  " > $OUTPUT
echo "### *Current modlist autogenerated from `./mods` directory at: `Wed Nov  8 18:18:48 CET 2023`*  " >> $OUTPUT

for filepath in `find ./mods -maxdepth 1 -mindepth 1 -type f| sort`; do
    path=`basename "$filepath"`
    echo "* $path" | sed -r 's/[-_]+/\ /g' | sed -r 's/\.jar//g' >> $OUTPUT
done

echo "Done"