name: Modlist build

on:
    push:
    workflow_dispatch:

jobs:
    modlist-build:
        runs-on: debian-latest

        steps:
            - uses: actions/checkout@v3
            
            - name: Build modlist file
              run: |
                touch modlist.md
                sh modlist_gen.sh
              shell: bash
